# mkdocs.yml

site_name: 'Will Smillie'
site_url: https://willsmillie.me
theme:
  name: material
  font:
    text: Kanit
  logo: img/icon.png
  favicon: img/icon.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: light
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
    - media: '(prefers-color-scheme: auto)'
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
