# mkdocs.yml

site_name: 'Will Smillie'
site_url: https://willsmillie.me/
theme:
  name: material
  palette:
    primary: deep purple
  font:
    text: Kanit

# Emoji Shortcode Plugins

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
